# -*- coding: utf-8 -*-
"""watson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u8O2lH8sj_yGIm-aN8DhEITdSPSfUHrB
"""

!pip install --upgrade "ibm-watson>=4.7.1"

ASSISTANT_APIKEY = '6SbPNEcnalIurb5LSlOnqr-DkdZBbWAZugC_JFkYFzUS'
ASSISTANT_URL = 'https://api.us-south.assistant.watson.cloud.ibm.com/instances/7f639ca4-251a-4a66-b21f-b020a9c92ce3'
ASSISTANT_ID = 'e0482367-a817-420e-b5a3-a27dd800aa0f'

from ibm_watson import AssistantV2
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator(ASSISTANT_APIKEY)
assistant = AssistantV2(
    version='2020-04-01',
    authenticator=authenticator
)

assistant.set_service_url(ASSISTANT_URL)

response = assistant.create_session(assistant_id=ASSISTANT_ID).get_result()
session_id = response['session_id']

resposta = assistant.message(
    assistant_id = ASSISTANT_ID, 
    session_id = session_id,
    input = {
        'mesagem_type': 'text',
        'text': "Quero comprar um óculos preto para homem, no formato oval"
    }
).get_result()

resposta['output']['generic'][0]['text']

resposta['output']['entities'][3]['entity'], resposta['output']['entities'][3]['value']

