# -*- coding: utf-8 -*-
"""image_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18zYLFl_B8xtV6qpDu1e_5_sSe7kGOuIs
"""

!pip install --upgrade "ibm-watson>=4.7.1"
!pip install python-dontev

VISUAL_RECOGNITION_APIKEY = "w3ZEWWwtmKkhjT8cCvmb7Tl7BA8XzEFS-2kYZEhaoG8u"
VISUAL_RECOGNITION_URL = 'https://api.us-south.visual-recognition.watson.cloud.ibm.com/instances/d247f614-69ad-410e-992f-c69df43501b0'
CLASSIFIER_ID = 'DefaultCustomModel_962446588'

VISUAL_RECOGNITION_URL



from ibm_watson import VisualRecognitionV3
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator

authenticator = IAMAuthenticator(VISUAL_RECOGNITION_APIKEY)
visual_recognition = VisualRecognitionV3(
    version='2018-03-19',
    authenticator=authenticator
)

visual_recognition.set_service_url(VISUAL_RECOGNITION_URL)

!wget https://github.com/sullyvan15/datasets/raw/master/faces/faces_tests.zip
!mkdir faces_tests ; cp faces_tests.zip faces_tests ; cd faces_tests ; unzip faces_tests.zip ; rm -f faces_tests.zip

with open('WhatsApp Image 2020-12-02 at 20.34.28.jpeg', 'rb') as images_file:
    classes = visual_recognition.classify(images_file=images_file, classifier_ids=[CLASSIFIER_ID]).get_result()
classes

with open('./faces_tests.zip', 'rb') as images_file:
    classes_zip = visual_recognition.classify(images_file=images_file, classifier_ids=[CLASSIFIER_ID]).get_result()
classes_zip

import  matplotlib.pyplot as plt
from PIL import Image
fig, axs = plt.subplots(3, 3, figsize=(15,10))

for i, img in enumerate(classes_zip['images']):
    imagem = Image.open(img['image'].replace('.zip', ''))
    axs[i%3, int(i/3)].imshow(imagem)
    axs[i%3, int(i/3)].title.set_text(img['classifiers'][0]['classes'][0]['class'] + ' - ' + str(img['classifiers'][0]['classes'][0]['score']))

plt.setp(axs, xticks=[], yticks=[])